// Auto-generated version constants
// This file is generated by scripts/generate-version.js

export const VERSION_INFO = {
  "version": "17753d2",
  "buildTime": "2025-06-13T10:25:23.789Z",
  "gitHash": "17753d2",
  "environment": "development"
} as const;

export const APP_VERSION = '17753d2';
export const BUILD_TIME = '2025-06-13T10:25:23.789Z';
export const GIT_HASH = '17753d2';
export const ENVIRONMENT = 'development' as 'development' | 'production' | 'test';

// Version checking utilities
export function isVersionOutdated(serverVersion: string): boolean {
  return APP_VERSION !== serverVersion;
}

export function getVersionDisplayString(): string {
  const date = new Date(BUILD_TIME).toLocaleDateString();
  const time = new Date(BUILD_TIME).toLocaleTimeString();
  
  if (ENVIRONMENT === 'development') {
    return `Dev (${date} ${time})`;
  }
  
  return `${APP_VERSION} (${date})`;
}
